#!/usr/bin/env python3
# post-checkout hook
import argparse
def parse_args():
  pass
def main(args=None):
  print("Hello from basic-python3.")
  pass
if __name__ == "__main__":
  args = parse_args()
main(args)
# exit 0
