#!/bin/sh
# prepare-commit-msg

#COMMIT_MSG_FILE=$1  # ".git/COMMIT_EDITMSG"
#COMMIT_SOURCE=$2    # "message"
#SHA1=$3             # ?
# echo "prepare-commit-msg: $(cat .git/COMMIT_EDITMSG)"
# SHA1=$SHA1" 
exit 0  # OK