#!/bin/sh
# git-c
# quick add + commit message pre-pended with your user id (Mac) or User name (Windows)
# by wilsonmar@gmail.com 310.320-7878
# usage: git c "messge here"

git add -A

if [ "$(uname)" == "Darwin" ]; then # In Mac OS X platform:
   git commit --message="@${USER}: $1"

elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then # In 32 bits Windows NT platform:
   # This not working yet: https://superuser.com/questions/1204589/how-to-use-windows-environment-variable-within-a-git-commit-message
   git commit --message="%COMPUTERNAME%: $1"
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then # In 64 bits Windows NT platform:
   git commit --message="%COMPUTERNAME%: $1"
   #git commit --message="{%COMPUTERNAME%}: $1"
   
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then # In GNU/Linux platform:
   # https://superuser.com/questions/944663/show-git-author-in-comments-while-writing-commit-message
   # From http://mfranc.com/tools/git-custom-command/ by Michal Franc
   # Show present working directory (PWD)
   git commit --message="@${PWD##*/}: $1"
fi